### ISSUE TITLE
RTL Support?

### ISSUE THREAD

**Issue by YektaDev** [florian-lefebvre/astro-loading-indicator#10]
Hi. Is there any plan to add support for RTL layouts? Specifically, when the HTML dir="rtl", the progress bar should start from the right side and fill towards the left, to align with RTL conventions.

Thanks!

**Comment by florian-lefebvre** [comment]
Sounds good to me! I'll do it later today :+1:

**Comment by YektaDev** [comment]
Well, that was unexpectedly quick! Thanks! 😃
