### ISSUE TITLE
The `is:global` keyword is added to builds

### ISSUE THREAD

**Issue by YektaDev** [florian-lefebvre/astro-loading-indicator#12]
During my investigation of HTML validation, I discovered that Astro’s `<style is:global>...</style>` inside components placed in the `<head>` is not stripped of `is:global` in the final bundle. I’m not sure if this behavior is intentional or a bug, but it leads to the following HTML validation error:

```
Attribute “is:global” not allowed on element “style” at this point.
```

**Questions**: 

- Is it necessary to retain the `is:global` attribute on this element in the final bundle?
- Normally, `is:global` disables Astro’s style scoping, but does this rule still apply in this specific context, or is there an exception for styles in the `<head>`?
- Would omitting the `is:global` attribute result in Astro’s default style scoping being applied to this style? If it's not the case, isn't it better to remove it in the style that's used for this component?

**Comment by florian-lefebvre** [comment]
Hi thanks for opening an issue! It's the first time I see this issue, would you mind sharing a minimal reproduction using https://astro.new?

**Comment by YektaDev** [comment]
Not at all, here it is, fresh out of the [oven](https://stackblitz.com/edit/github-wdcfns?file=dist%2Findex.html)!
Hmm... I always wondered why no one seems to be bothered by this issue. 
I literally just created an empty project and followed the [installation instructions](https://github.com/florian-lefebvre/astro-loading-indicator/blob/main/package/README.md). I also submitted a [bug report](https://github.com/withastro/astro/issues/12434) while I was at it; this may be an actual bug.

**Comment by florian-lefebvre** [comment]
I see what the issue is, I never noticed it before! I'm going to publish a patch very soon

**Comment by YektaDev** [comment]
The feedback loop from the issue to a new release is insane! Thanks!
