### ISSUE TITLE
nprogress

### ISSUE THREAD

**Issue by millette** [florian-lefebvre/astro-loading-indicator#2]
The `nprogress` dep is [incredibly old](https://github.com/rstacruz/nprogress/releases) in web terms. There is a [new version in progress](https://github.com/rstacruz/nprogress/pull/218) but that effort stalled 4 years ago.

I know it's incredibly popular with 2600 npm dependents but I can't help but think a brand new replacement would be ideal.

Maybe it's only tangentially related to this project, but then again, maybe this would be a good starting place for an nprogress replacement.

Thoughts?

**Comment by florian-lefebvre** [comment]
Why not! If you have any better alternative, I'm open to updating the package!

**Comment by martrapp** [comment]
@millette If you are looking for a more recent nprogress replacement, you might want to take a look at [the &lt;ProgressBar /&gt; component](https://events-3bg.pages.dev/loading/progress-bar) of the [Bag of Tricks](https://www.npmjs.com/package/astro-vtbot). This is build upon the [swup progress plugn](https://github.com/swup/progress-plugin/blob/master/CHANGELOG.md) v3.1.2 as of September 2023.

**Comment by millette** [comment]
@martrapp Oh, great! I had a hard time believing noone had come up with a replacement for the good old nprogress and I couldn't find one. I was about to write my own, so thanks!

@florian-lefebvre I'm gonna have a look later this week and see if I can integrate the ProgressBar component directly or the swup plugin or if I really need to write my own small replacement.

**UPDATE:** Here's a direct link to demo the progress bar component: <https://events-3bg.pages.dev/loading/progress-bar/one/>
