### ISSUE TITLE
PSA: Updating to @swup/progress-plugin 3.2.0 breaks the indicator

### ISSUE THREAD

**Issue by dallyh** [florian-lefebvre/astro-loading-indicator#5]
This is just a PSA for future. I had @swup/progress-plugin 3.2.0 installed in my project, and I decided to use this integration. However the progress bar was shown but never finished till the end.

So I cloned this repo, updated the plugin and observed the same behavior See here: https://github.com/dallyh/astro-loading-indicator.

Just install dependencies, and run the playground. Click the "about" link and observe that the indicator never finishes.

I currently did not dive deeper into this.

**Comment by florian-lefebvre** [comment]
Thanks for letting me know! I need to check their changelog (here's the diff https://github.com/swup/progress-plugin/compare/3.1.2...3.2.0)

**Comment by florian-lefebvre** [comment]
I just released `0.4.0` of the package, which removes the dependency entirely
